version: "3.8"

services:
  django:
    build:
      context: ./loanapp
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./loanapp:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=loanapp.settings

  react:
    build:
      context: ./loan-calculator
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./loan-calculator/src:/app/src
    depends_on:
      - django
